from django.urls import path

from .views import (
    cabinet_abc,
    cabinet_api_status,
    cabinet_bot_chats,
    cabinet_bot_settings_save,
    cabinet_catalog,
    cabinet_day_sales,
    cabinet_debtor_pay,
    cabinet_debtors,
    cabinet_label_template,
    cabinet_products_export,
    cabinet_products_import,
    cabinet_range_stats,
    cabinet_reports,
    cabinet_shift_detail,
    cabinet_shifts,
    cabinet_telegram_sync,
    cabinet_top_stats,
    cabinet_view,
    cabinet_warm,
    download_installer,
    telegram_cron_sync,
)

app_name = "accounts"

urlpatterns = [
    path("cabinet/", cabinet_view, name="cabinet"),
    path("download/", download_installer, name="download_installer"),
    path("cabinet/range-stats/", cabinet_range_stats, name="cabinet_range_stats"),
    path("cabinet/top-stats/", cabinet_top_stats, name="cabinet_top_stats"),
    path("cabinet/api-status/", cabinet_api_status, name="cabinet_api_status"),
    path("cabinet/catalog/", cabinet_catalog, name="cabinet_catalog"),
    path("cabinet/warm/", cabinet_warm, name="cabinet_warm"),
    path("cabinet/day-sales/", cabinet_day_sales, name="cabinet_day_sales"),
    path("cabinet/shifts/", cabinet_shifts, name="cabinet_shifts"),
    path("cabinet/reports/", cabinet_reports, name="cabinet_reports"),
    path("cabinet/abc/", cabinet_abc, name="cabinet_abc"),
    path("cabinet/shift-detail/", cabinet_shift_detail, name="cabinet_shift_detail"),
    path("cabinet/products-import/", cabinet_products_import, name="cabinet_products_import"),
    path("cabinet/products-export/", cabinet_products_export, name="cabinet_products_export"),
    path("cabinet/bot-settings/", cabinet_bot_settings_save, name="cabinet_bot_settings_save"),
    path("cabinet/bot-chats/", cabinet_bot_chats, name="cabinet_bot_chats"),
    path("cabinet/telegram-sync/", cabinet_telegram_sync, name="cabinet_telegram_sync"),
    path("cabinet/telegram-cron/", telegram_cron_sync, name="telegram_cron_sync"),
    path("cabinet/label-template/", cabinet_label_template, name="cabinet_label_template"),
    path("cabinet/debtors/", cabinet_debtors, name="cabinet_debtors"),
    path("cabinet/debtors/pay/", cabinet_debtor_pay, name="cabinet_debtor_pay"),
]
