from django.urls import path

from .client_debts import (
    cabinet_client_debt_adjust,
    cabinet_client_debtor_delete,
    cabinet_client_debtor_save,
    cabinet_client_debts,
    cabinet_sms_template,
    cabinet_sms_template_save,
)
from .suppliers import (
    cabinet_supplier_delete,
    cabinet_supplier_ledger,
    cabinet_supplier_product,
    cabinet_supplier_save,
    cabinet_suppliers,
    cabinet_suppliers_export,
    cabinet_suppliers_history,
    cabinet_suppliers_summary,
)
from .views import (
    cabinet_abc,
    cabinet_api_status,
    cabinet_bot_chats,
    cabinet_bot_settings_save,
    cabinet_catalog,
    cabinet_day_sales,
    cabinet_day_sales_export,
    cabinet_debtor_pay,
    cabinet_debtors,
    cabinet_label_template,
    cabinet_products_export,
    cabinet_products_import,
    cabinet_range_stats,
    cabinet_reports,
    cabinet_sale_detail,
    cabinet_shift_detail,
    cabinet_shifts,
    cabinet_stock_in,
    cabinet_telegram_sync,
    cabinet_top_export,
    cabinet_top_stats,
    cabinet_view,
    cabinet_warm,
    download_installer,
    telegram_cron_sync,
)

app_name = "accounts"

urlpatterns = [
    path("cabinet/", cabinet_view, name="cabinet"),
    path("download/", download_installer, name="download_installer"),
    path("cabinet/range-stats/", cabinet_range_stats, name="cabinet_range_stats"),
    path("cabinet/top-stats/", cabinet_top_stats, name="cabinet_top_stats"),
    path("cabinet/top-stats/export/", cabinet_top_export, name="cabinet_top_export"),
    path("cabinet/stock-in/", cabinet_stock_in, name="cabinet_stock_in"),
    path("cabinet/api-status/", cabinet_api_status, name="cabinet_api_status"),
    path("cabinet/catalog/", cabinet_catalog, name="cabinet_catalog"),
    path("cabinet/warm/", cabinet_warm, name="cabinet_warm"),
    path("cabinet/day-sales/", cabinet_day_sales, name="cabinet_day_sales"),
    path("cabinet/day-sales/export/", cabinet_day_sales_export, name="cabinet_day_sales_export"),
    path("cabinet/sale-detail/", cabinet_sale_detail, name="cabinet_sale_detail"),
    path("cabinet/shifts/", cabinet_shifts, name="cabinet_shifts"),
    path("cabinet/reports/", cabinet_reports, name="cabinet_reports"),
    path("cabinet/abc/", cabinet_abc, name="cabinet_abc"),
    path("cabinet/shift-detail/", cabinet_shift_detail, name="cabinet_shift_detail"),
    path("cabinet/products-import/", cabinet_products_import, name="cabinet_products_import"),
    path("cabinet/products-export/", cabinet_products_export, name="cabinet_products_export"),
    path("cabinet/bot-settings/", cabinet_bot_settings_save, name="cabinet_bot_settings_save"),
    path("cabinet/bot-chats/", cabinet_bot_chats, name="cabinet_bot_chats"),
    path("cabinet/telegram-sync/", cabinet_telegram_sync, name="cabinet_telegram_sync"),
    path("cabinet/telegram-cron/", telegram_cron_sync, name="telegram_cron_sync"),
    path("cabinet/label-template/", cabinet_label_template, name="cabinet_label_template"),
    path("cabinet/debtors/", cabinet_debtors, name="cabinet_debtors"),
    path("cabinet/debtors/pay/", cabinet_debtor_pay, name="cabinet_debtor_pay"),
    path("cabinet/client-debts/", cabinet_client_debts, name="cabinet_client_debts"),
    path("cabinet/client-debts/save/", cabinet_client_debtor_save, name="cabinet_client_debtor_save"),
    path("cabinet/client-debts/delete/", cabinet_client_debtor_delete, name="cabinet_client_debtor_delete"),
    path("cabinet/client-debts/adjust/", cabinet_client_debt_adjust, name="cabinet_client_debt_adjust"),
    path("cabinet/sms-template/", cabinet_sms_template, name="cabinet_sms_template"),
    path("cabinet/sms-template/save/", cabinet_sms_template_save, name="cabinet_sms_template_save"),
    path("cabinet/suppliers/", cabinet_suppliers, name="cabinet_suppliers"),
    path("cabinet/suppliers/summary/", cabinet_suppliers_summary, name="cabinet_suppliers_summary"),
    path("cabinet/suppliers/history/", cabinet_suppliers_history, name="cabinet_suppliers_history"),
    path("cabinet/suppliers/export/", cabinet_suppliers_export, name="cabinet_suppliers_export"),
    path("cabinet/suppliers/save/", cabinet_supplier_save, name="cabinet_supplier_save"),
    path("cabinet/suppliers/delete/", cabinet_supplier_delete, name="cabinet_supplier_delete"),
    path("cabinet/suppliers/product/", cabinet_supplier_product, name="cabinet_supplier_product"),
    path("cabinet/suppliers/ledger/", cabinet_supplier_ledger, name="cabinet_supplier_ledger"),
]
