# Generated by Django 5.1.7 on 2026-08-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='telegram_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='telegram_notified_events',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='telegram_notify_close',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='telegram_notify_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='telegram_recipients',
            field=models.TextField(blank=True, default='', help_text='Har qator: chat id, @username, guruh/kanal linki'),
        ),
    ]
