# Generated by Django 5.1.7 on 2026-08-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegram_bot_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopInstaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TezPOS Setup', max_length=120)),
                ('version', models.CharField(blank=True, default='', max_length=40)),
                ('file', models.FileField(upload_to='installers/')),
                ('is_active', models.BooleanField(default=True, help_text='Faol bo‘lsa, saytdagi Install shu faylni yuklaydi.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Desktop installer (.exe)',
                'verbose_name_plural': 'Desktop installerlar',
                'ordering': ['-updated_at'],
            },
        ),
    ]
