# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_desktop_installer"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantprofile",
            name="tezpos_api_token",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tenantprofile",
            name="tezpos_server_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
