# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_tenantprofile_tezpos_api_creds"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("shop_key", models.CharField(db_index=True, max_length=140, unique=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, default="", max_length=180)),
            ],
            options={
                "verbose_name": "Narx belgisi shabloni",
                "verbose_name_plural": "Narx belgisi shablonlari",
            },
        ),
    ]
