# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_label_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantprofile",
            name="telegram_last_sync",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="tenantprofile",
            name="tezpos_server_name",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddIndex(
            model_name="tenantprofile",
            index=models.Index(
                fields=["telegram_enabled", "tezpos_server_name"],
                name="acct_tenant_tg_sync_idx",
            ),
        ),
    ]
