# Generated by Django 5.1.7 on 2026-08-21 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tenant_telegram_sync_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_key', models.CharField(db_index=True, max_length=140)),
                ('name', models.CharField(max_length=180)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['shop_key', 'name'], name='acct_supplier_shop_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('shop_key', 'name'), name='acct_supplier_shop_name_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SupplierLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('we_owe', 'Biz qarz oldik'), ('they_owe', 'Taminotchi qarz'), ('we_pay', 'Biz to‘ladik'), ('they_pay', 'Ular to‘ladi')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('signed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.CharField(blank=True, default='', max_length=180)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='accounts.supplier')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['supplier', '-created_at'], name='acct_supled_sup_dt_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, default='', max_length=64)),
                ('product_name', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.supplier')),
            ],
            options={
                'ordering': ['product_name'],
                'indexes': [models.Index(fields=['supplier', 'product_name'], name='acct_supprod_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'product_id', 'product_name'), name='acct_supprod_uniq')],
            },
        ),
    ]
