# Generated by Django 5.1.7 on 2026-08-21 20:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtSmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_key', models.CharField(db_index=True, max_length=140, unique=True)),
                ('title', models.CharField(default='Qarzdorlik', max_length=120)),
                ('shop_label', models.CharField(blank=True, default='', help_text='SMS boshidagi do‘kon nomi (bo‘sh bo‘lsa biznes nomi)', max_length=180)),
                ('body', models.TextField(default="{shop}:\nQarzdorligingiz : {amount} so'm.\nIltimos, qarzdorlikni to'lashni unutmang.")),
                ('is_approved', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DevSMS qarz shabloni',
                'verbose_name_plural': 'DevSMS qarz shablonlari',
            },
        ),
        migrations.CreateModel(
            name='ClientDebtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_key', models.CharField(db_index=True, max_length=140)),
                ('name', models.CharField(max_length=180)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('note', models.CharField(blank=True, default='', help_text='Do‘kon / izoh (masalan: Kokcha market)', max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['shop_key', 'name'], name='acct_clidebt_shop_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientDebtorLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('add', 'Qarz qo‘shildi'), ('sub', 'Qarz ayirildi')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('signed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.CharField(blank=True, default='', max_length=180)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sms_sent', models.BooleanField(default=False)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='accounts.clientdebtor')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['debtor', '-created_at'], name='acct_clidebt_led_dt_idx')],
            },
        ),
    ]
