# Generated by Django 5.1.7 on 2026-08-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_client_debts_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtsmstemplate',
            name='body',
            field=models.TextField(default="{shop} - {branch}\n\nQarz: {amount} so'm\n\nQoldiq: {balance} so'm\n\nChek:\n{check_link}"),
        ),
        migrations.AlterField(
            model_name='desktopinstaller',
            name='file',
            field=models.FileField(blank=True, help_text='TezPOS Setup .exe faylini yuklang.', upload_to='installers/'),
        ),
    ]
