# Generated by Django 5.1.7 on 2026-08-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
