# Generated by Django 5.1.7 on 2026-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_min_stock_default_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Shtrix-kod')),
                ('name', models.CharField(max_length=180, verbose_name='Nomi')),
                ('unit', models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('litr', 'litr'), ('quti', 'quti'), ('metr', 'metr')], default='dona', max_length=20, verbose_name='O‘lchov birligi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='barcode_catalog/', verbose_name='Rasm')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shtrix-kod bazasi',
                'verbose_name_plural': 'Shtrix-kod bazasi',
                'ordering': ['-updated_at', 'name'],
            },
        ),
    ]
